### PR TITLE
Issue24 add test cases

### PR DESCRIPTION
**Pull request by AntoineGautier**
This pull request covers:

- Unit tests (using CTest)
- Cross-platform compilation with CMake (closes [issue1](https://github.com/lbl-srg/funnel/issues/1))

Note:

- No executable delivered: only libraries and Python binding.
- No build available for x86 architectures yet: further work needed 

Dependencies and licensing:

- CMake: build system [BSD 3-clause](https://cmake.org/licensing/)
- Pandas: used for testing [BSD 3-clause](http://pandas.pydata.org/pandas-docs/stable/overview.html#license)
- Plotly: used by the plot function `plot_funnel` [MIT](https://github.com/plotly/plotly.js/blob/master/LICENSE)

### CODE REVIEW

**Comment by devil-d3** [comment]
@AntoineGautier  in your pyfunnel.py file..... while compiling gives an type error
The following is the error generated while executing the python code on windows

_Traceback (most recent call last):
  File "pyfunnel.py", line 163, in compareAndReport
    tol['rtoly'])
ctypes.ArgumentError: argument 7: <class 'TypeError'>: wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyfunnel.py", line 480, in <module>
    rtoly=args.rtoly,
  File "pyfunnel.py", line 165, in compareAndReport
    raise RuntimeError("Library call raises exception: {}".format(e))
RuntimeError: Library call raises exception: argument 7: <class 'TypeError'>: wrong type_

**Comment by AntoineGautier** [comment]
@devil-d3 you write "while compiling" meaning you tried to build the library on Windows with CMake and got the error while running the tests?
Could you please provide:

- the command you used to get this error;
- the output of the following command: `python -c 'import sys,platform; print(platform.architecture(), sys.maxsize > 2**32, platform.python_version())'`

**Comment by devil-d3** [comment]
The command I used to compile pyfunnel.py is 

Python pyfunnel.py --reference <filename> --test <filename> --atolx 0.002 --atoly 0.002  --output <directory name>

And I got that type error

**Comment by devil-d3** [comment]
1. The command i used is

Python pyfunnel.py --reference "<filename>" --test "<filename>" --atolx 0.002 --atoly 0.002 --output 

And I got that type error

**Comment by AntoineGautier** [comment]
@devil-d3 what git branch are you working with: `master` or `issue24_addTestCases`?
The command you provided returns the following on Windows 10 x64:
`pyfunnel.py: error: argument --reference: expected one argument`
This is because you need to provide a valid file path for the keyword arguments `reference` and `test`. `output` is optional but if provided it should be a valid directory path (not `None`). You might check the documentation again for instructions regarding how to run.

**Comment by devil-d3** [comment]
the

> @devil-d3 you write "while compiling" meaning you tried to build the library on Windows with CMake and got the error while running the tests?
> Could you please provide:
> 
> * the command you used to get this error;
> * the output of the following command: `python -c 'import sys,platform; print(platform.architecture(), sys.maxsize > 2**32, platform.python_version())'`

output of the above command you specified 
'64bit', 'WindowsPE') True 3.7.2

**Comment by devil-d3** [comment]
> @devil-d3 what git branch are you working with: `master` or `issue24_addTestCases`?
> The command you provided returns the following on Windows 10 x64:
> `pyfunnel.py: error: argument --reference: expected one argument`
> This is because you need to provide a valid file path for the keyword arguments `reference` and `test`. `output` is optional but if provided it should be a valid directory path (not `None`). You might check the documentation again for instructions regarding how to run.

1.I have been using issue24_addTestCases 
2. python pyfunnel.py --reference C:\Users\Dell\Desktop\New folder\reference.csv  --test C:\Users\Dell\Desktop\New folder\test.csv --atolx 0.002  --atoly 0.002 --output C:\Users\Dell\Desktop\New folder\result
this is the exact command what i'm using

**Comment by devil-d3** [comment]
> @devil-d3 what git branch are you working with: `master` or `issue24_addTestCases`?
> The command you provided returns the following on Windows 10 x64:
> `pyfunnel.py: error: argument --reference: expected one argument`
> This is because you need to provide a valid file path for the keyword arguments `reference` and `test`. `output` is optional but if provided it should be a valid directory path (not `None`). You might check the documentation again for instructions regarding how to run.

the issue here is it is showing an type error ... we need to deal with this

**Comment by AntoineGautier** [comment]
OK this might be related with Python 3. Tests have only been carried out with Python 2 yet.

**Comment by devil-d3** [comment]
Ok... Gud work
And thanks for the instinct replys... looking forward to work with you on this

**Pull request merged**
