### PR TITLE
Issue61 mac os universal

### LINKED ISSUE #61: arm64 support for macOS
On an M1 processor I get:
```
RuntimeError: Could not load funnel library with this path: /opt/homebrew/lib/python3.9/site-packages/pyfunnel/lib/darwin64/libfunnel.dylib. dlopen(/opt/homebrew/lib/python3.9/site-packages/pyfunnel/lib/darwin64/libfunnel.dylib, 0x0006): tried: '/opt/homebrew/lib/python3.9/site-packages/pyfunnel/lib/darwin64/libfunnel.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

I'll propose a fix!

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #61.
(The universal build for macOS is configured in `CMakeLists.txt` and thus automatically generated via GH actions.)

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@JayHuLBL Can you review this little change? And test it on macOS x64 if you have an available machine?

**Comment by AntoineGautier** [comment]
I increased the version to 1.0.0 (I believe the tool has been used enough to leave beta stage).
I also updated the doc and change log.

TODO once this is merged on master:

- [ ] Release on PyPI

**Comment by JayHuLBL** [comment]
@AntoineGautier I will test the change later today. I believe I do have one Mac at home, with M1 chip.

**Comment by AntoineGautier** [comment]
@JayHuLBL Great, thanks! Note that I have already tested it on macOS arm64. I was rather asking for a test on macOS x86_64, but looking at https://docs.github.com/fr/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, it seems that GH-hosted runner for macOS is on x86_64 architecture. So, since the tests passed with GH actions, I believe we are good. Please double check locally on macOS x86_64 if you have a machine.

**Comment by JayHuLBL** [comment]
@AntoineGautier I tested it on my MacBook which is the x86-64. It works fine. I believe the change is good to merge.

**Pull request merged**
