### PR TITLE
arm64 support for #61

### PR DESCRIPTION
**Pull request by Mathadon**
for #61 

The file was created as follows:

```
mkdir build
cd build
cmake ..
make
lipo -create -output libfunnel.dylib src/libfunnel.dylib ../pyfunnel/lib/darwin64/libfunnel.dylib
cp  libfunnel.dylib ../pyfunnel/lib/darwin64/libfunnel.dylib
lipo -archs ../pyfunnel/lib/darwin64/libfunnel.dylib 
> x86_64 arm64
```

The first lipo command generates a universal binary by combining the newly created dylib file (arm64) and the file that was originally in the repository (x86_64).

Source: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

### CODE REVIEW

**Comment by mwetter** [comment]
@Mathadon : Thanks for the changes.

@JayHuLBL : Can you please update the build rules so next time we create the same format, and also merge this change to BuildingsPy.

**Comment by JayHuLBL** [comment]
@Mathadon Hello Fillip, is there any difference to generate the dylib file in arm64 Mac? I'd like include the option to the build rule.

**Comment by Mathadon** [comment]
@JayHuLBL Hey! I think that cmake automatically builds the correct binary depending on the host system. So the commands are the same but the system is not. You can probably force cmake to build the arm64 version but I don't know how. 🤷‍♂️

**Comment by AntoineGautier** [comment]
@Mathadon I propose to build it directly with CMake in #68.

**Comment by JayHuLBL** [comment]
This issue can be closed as it has been addressed through PR #68.

**Pull request closed without merging**
